ByteInternet/hypernode-deploy

- src/Command/Build.php
- src/Command/ComposerAuth.php
- src/Command/Deploy.php
- src/Command/RunTask.php
- src/DeployRunner.php
This allows the `run-task` command to deploy some file to a server for example: https://github.com/HipexBV/hipex-services-zendesk-auth-gateway/blob/alpha/deploy.php
> feat: Allow `run-task` command to configure server / build stage

- src/Deployer/Task/Deploy/PrepareTask.php
- src/Deployer/Task/Deploy/UploadTask.php
This caused the `deploy:cleanup` task to remove the just deployed release
> stage/deploy: Fix running `deploy:release` twice

- src/Deployer/Task/Deploy/LinkTask.php
If there's already a lingering public symlink, don't try to redo the symlink. Only do so if it doesn't exist yet
> Don't try public symlink if it already exists

- README.md
add instructions to the README.md on how to build and use a local image (for development)
> add instructions to build and run local image

- src/Deployer/Task/PlatformConfiguration/NginxSyncTask.php
- src/Deployer/Task/PlatformConfiguration/SupervisorUploadTask.php
Fixes issues where Nginx tries to rsync to the `.hypernode/nginx` dir
> Ensure .hypernode exists

- ci/release_semantic_versions.sh
> Backport #24: ci: Fix non-templated tag spec in release_semantic_versions.sh

- ci/build/Dockerfile
Some build systems require Python to be available. As most of the industry has moved on to Python 3, let's install just that and use that version as the default `python` executable.
> Install python3 as default python executable

- ci/build/Dockerfile
This is a forwardport of #72.
Some build systems require Python to be available. As most of the industry has moved on to Python 3, let's install just that and use that version as the default python executable.
> Forwardport: Install python3 as default python executable

- src/Brancher/BrancherHypernodeManager.php
in the event where there is not enough compute capacity available the system will start creating new cloud resources on the fly. in that case we should not give up too quickly but wait a bit longer.
to address:
```
Run hypernode-deploy deploy acceptance -vvv
[info] Creating an brancher Hypernode based on mytesthypernodename.
[info] Successfully requested brancher Hypernode, name is mytesthypernodename-ephmabci8.
[info] Waiting for brancher Hypernode to become available...
Got an expected exception during the allowed error window of HTTP code 404, waiting for mytesthypernodename-ephmabci8 to become available[info] Stopping brancher Hypernode mytesthypernodename-ephmabci8...
In BrancherHypernodeManager.php line 132:
[Hypernode\Deploy\Exception\TimeoutException] …
```
> increase brancher node wait timeout

- ci/build/Dockerfile
We use this very often when deploying python applications with Hypernode Deploy
> ci/image: Install virtualenv

- src/DeployRunner.php
- src/Deployer/Task/After/AfterTaskGlobal.php
- src/Deployer/Task/After/CachetoolTask.php
- src/Deployer/Task/Deploy/CopyTask.php
- src/Deployer/Task/Deploy/DeployTask.php
- src/Deployer/Task/Deploy/DeployTaskGlobal.php
- src/Deployer/Task/Deploy/FinalizeTask.php
- src/Deployer/Task/Deploy/LinkTask.php
- src/Deployer/Task/Deploy/UploadTask.php
In the future, when we reiterate on Hypernode Deploy for clusters, we'll see what we really need and what's best to do. For now, it doesn't make sense to keep this in here.
> Remove roles selector from builtin tasks

- src/Deployer/TaskBuilder.php
Follow-up for #79. With this, we can deprecate all the role stuff from [ByteInternet/hypernode-deploy-configuration](https://github.com/ByteInternet/hypernode-deploy-configuration/).
> Remove roles selector from builtin tasks in TaskBuilder

- ci/test/run-brancher.sh
- src/Brancher/BrancherHypernodeManager.php
- src/Command/Build.php
- src/Command/ComposerAuth.php
- src/Command/Deploy.php
- src/Command/RunTask.php
- src/DeployRunner.php
Useful for doing rapid development, and you don't care too much about pristine environments. Instead of creating a new Brancher node when using `addBrancherServer`, just reuse the last one if there is any.
Note the new `--reuse-brancher` flag:
```
$ hypernode-deploy deploy -h
Description:
Deploy application.
Usage:
deploy [options] [--] <stage>
Arguments:
stage                 Stage deploy to
Options:
--reuse-brancher  Reuse the brancher Hypernode from the previous deploy
-h, --help            Display help for the given command. When no command is given display help for the list command
-q, --quiet           Do not output any message
-V, --version         Display this application version
--ansi|--no-ansi  Force (or disable --no-ansi) ANSI output
-n, --no-interaction  Do not ask any …
```
> Allow reusing of previous brancher instance

- src/DeployRunner.php
Works like this:
```
$ hypernode-deploy deploy production
task deploy:info
[production:example.hypernode.io] info deploying HEAD
task prepare:ssh
task deploy:info
[production:example.hypernode.io] info deploying HEAD
task deploy:setup
task deploy:lock
task deploy:release
task deploy:shared
task deploy:writable
task deploy:copy:code
^C[warning] Received signal SIGINT, running fail jobs
[production:example.hypernode.io]  error  in CopyTask.php on line 20:
[production:example.hypernode.io] run readlink /data/web/apps/example/release
[production:example.hypernode.io] exit code -1 (Unknown error)
task deploy:failed
task deploy:unlock
```
> DeployRunner: Add SIGINT handler to run fail tasks

- ci/test/magento/deploy1.php
- ci/test/run-general.sh
- src/Brancher/BrancherHypernodeManager.php
- src/DeployerLoader.php
- src/Printer/GithubWorkflowPrinter.php
If a task writes a [GitHub Workflow command](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions), it gets prefixed with the `[host]`, which renders it useless for GitHub. With this PR, it detects a GitHub Workflow command being written to the output and writes it directly (without any decorators) to the output interface.
The integration test summary should show a debug message with content:
```
This message should pass through to Github Workflow Summary!
```
Ideally we fix this in Deployer, but let's explore this idea first and see how it performs.
> Deployer: Pass-through GitHub Workflow commands

- src/Printer/GithubWorkflowPrinter.php
Lines can come in in batches of multiple lines, so we need to match that for it to properly detect the workflow commands in the callback function
> GithubWorkflowPrinter: Match workflow command in multiline string buffer

- src/Bootstrap.php
We don't need any escaping, because the Twig template engine only supplies escaping for web-related assets.
See the `autoescape` option described here: https://twig.symfony.com/doc/2.x/api.html#environment_options
> twig: Disable autoescape

- .github/workflows/publish.yaml
- .github/workflows/test.yaml
- ci/test/run-general.sh
Also bump other default settings from 8.1 to 8.2
> ci: Build PHP 8.3 image

- src/Deployer/Task/PlatformConfiguration/RedisEnableTask.php
- src/Deployer/Task/PlatformConfiguration/VarnishEnableTask.php
Resolves a blocking error during deploy when switching varnish versions
```
[production:******.hypernode.io]  error  in VarnishEnableTask.php on line 39:
[production:******.hypernode.io] run hypernode-systemctl settings varnish_version 6.0 --block
[production:******.hypernode.io] err Traceback (most recent call last):
[production:******.hypernode.io] err File "/usr/bin/hypernode-systemctl", line 11, in <module>
[production:******.hypernode.io] err load_entry_point('kamikaze3==20240215.10[140](*****)5', 'console_scripts', 'hypernode-systemctl')()
[production:******.hypernode.io] err File "/usr/lib/python3/dist-packages/kamikaze3/systemctl/main.py", line 132, in main
[production:******.hypernode.io] err args = parse_arguments(args=args)
[production:******.hypernode.io] err File …
```
> fix: resolve blocking error when switching versions

- .github/workflows/publish.yaml
This will make Node.js 20 for all supported PHP versions available
> ci: Add Node.js 20 to build matrix

- src/Deployer/Task/PlatformConfiguration/CronSyncTask.php
Environment variables were disappearing after crontab is synced.
Should be fixed now by properly escaping.
Assuming cron job which gets deployed.
```
MAGENTO_DOCROOT=/data/web/apps/mydomain.com/current
MAGENTO_PHPBIN=php
0 4 * * * cd $MAGENTO_DOCROOT && $MAGENTO_PHPBIN ./bin/magento foo-bar
```
After deployment on the server crontab is as follows:
```
MAGENTO_DOCROOT=/data/web/apps/mydomain.com/current
MAGENTO_PHPBIN=php
0 4 * * * cd && ./bin/magento foo-bar
```
This PR fixes the issue.
> fix cronjob sync escaping issue with env vars

- .github/workflows/test.yaml
By running the test workflow on the base repository, a contributor can make use of our integration tests etc.
> ci: Run test workflow on base repository

- .github/workflows/test.yaml
Commit 17806306 set the pull request event to `pull_request_target`, which means the pipelines run on the base ref with the secrets from base as well. That's all fine, but we actually want to test the code on the pull request ref
> ci: Checkout pull request ref instead

- src/DeployRunner.php
The master branch contains a few regressions:
- Accidental variable type mixing (https://github.com/ByteInternet/hypernode-deploy/pull/113/commits/3cad9f278abff473a4e8bd8807d73e9c116c67cf)
`PHP Fatal error:  Uncaught Error: Call to undefined method Deployer\Task\Task::supports() in phar:///bin/hypernode-deploy/src/DeployRunner.php:150`
- Role selection does not work as intended, causing certain tasks to be skipped (https://github.com/ByteInternet/hypernode-deploy/pull/113/commits/c4000f681474aad8490cbc603b4f46a221335ced)
> Fix regressions

- .github/workflows/test.yaml
Reverts ByteInternet/hypernode-deploy#111
Not working as expected, just builds master instead of the pull_request_target event revision
> Revert "ci: Run test workflow on base repository"

- ci/build/Dockerfile
Fixes `fatal: detected dubious ownership in repository at ...` issues some users experience when using Hypernode Deploy
> Add safe directory wildcard to dockerfiles

- bin/hypernode-deploy.php
You can still use this functionality if you need it with:
```
DEPLOY_AUTOLOAD_PATH=./vendor/autoload.php hypernode-deploy build
```
> Don't automatically autoload app vendor autoloader

- ci/build/Dockerfile
Appearantly the node 20 APT package already comes with npm, so we dont have to install it here
> Only install npm through APT when node version is under 20

- src/Command/Tree.php
- src/DeployRunner.php
Example output:
```
» hypernode-deploy tree deploy     
The task-tree for deploy:
├── slack:notify  // before deploy
└── deploy
├── deploy:upload
│   ├── prepare:ssh
│   ├── deploy:info
│   ├── deploy:prepare
│   │   ├── deploy:info
│   │   ├── deploy:setup
│   │   ├── deploy:lock
│   │   ├── deploy:release
│   │   ├── deploy:shared
│   │   └── deploy:writable
│   ├── deploy:copy
│   │   ├── deploy:copy:code
│   │   └── deploy:shared
│   └── deploy:deploy
├── deploy:link
│   ├── deploy:symlink
│   ├── cachetool:clear:opcache  // after deploy:symlink
│   ├── cachetool:cleanup  // after cachetool:clear:opcache
│   └── deploy:public_link
└── deploy:finalize
├── deploy:after
├── deploy:unlock
├── deploy:cleanup
└── deploy:success
└── slack:notify:success  // after deploy:success
```
> Add 'tree' command to Hypernode Deploy to get overview and list of tasks for a stage
